# Site settings
title: GeoModels
description: Package for statistical analysis of geo-referenced spatial and spatio-temporal data
#cover: assets/images/under_construction.jpg
logo: assets/images/under_construction.jpg
#favicon: assets/images/about.png
baseurl: "/GeoModels-page/" # the subpath of your site, e.g. /blog/ or / for root url: "https://victormoralesonate.github.io" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

<figure class="ampstart-image-with-heading  m0 relative mb4">
<amp-img src="{{ site.baseurl }}assets/images/about.jpg" width="600" height="400" layout="responsive" alt="" class="mb3"></amp-img>
<figcaption class="absolute right-0 bottom-0 left-0">
</figcaption>
</figure>

# Social
facebook: facebook
twitter: twitter
github:  github

#Additional Pages
tutorials: tutorials
resources: resources
install: install
citation: citation
authors: authors
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
parse_block_html: true

plugins:
- jekyll-paginate


# Settings for rake task
safe: False
lsi: False
username: VictorMoralesOnate #github username
repo: GeoModels-page #github repository
branch: master #branch
relative_source: ../GeoModels-page/ #source directory
destination: ../vmoprojs/GeoModels-page/ #destination directory
production_url:  https://victormoralesonate.github.io
source_url:  https://github.com/VictorMoralesOnate #source repository url

exclude:
- README.md
- Rakefile
- Gemfile
- Gemfile.lock
- changelog.md
- "*.Rmd"
- vendor
- .travis.yml
