# Site settings
title: GeoModels
description: Package for spatial and spatio-temporal modelling using composite likelihood.
# cover: assets/images/radhakrishna.jpg
# logo: assets/images/logo.png
# favicon: assets/images/favicon.png
baseurl: "/GeoModels/" # the subpath of your site, e.g. /blog/ or / for root url: "https://victormoralesonate.github.io" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

# Social
facebook: facebook
twitter: twitter
github:  github

#Additional Pages
resources: resources
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
parse_block_html: true

plugins:
- jekyll-paginate


# Settings for rake task
safe: False
lsi: False
username: VictorMoralesOnate #github username
repo: GeoModels #github repository
branch: master #branch
relative_source: ../GeoModels/ #source directory
destination: ../VictorMoralesOnate/GeoModels/ #destination directory
production_url:  https://victormoralesonate.github.io
source_url:  https://github.com/VictorMoralesOnate #source repository url

exclude:
- README.md
- Rakefile
- Gemfile
- Gemfile.lock
- changelog.md
- "*.Rmd"
- vendor
- .travis.yml
