# Site settings
title: GeoModels
description: Package for spatial and spatio-temporal modelling using composite likelihood.

This package provides a set of procedures for

a. simulation and estimation of some spatial and spatio-temporal random fields using standard likelihood and a likelihood approximation method called composite likelihood and

b. prediction using best linear unbiased prediction.  Spatio (temporal) bivariate data estimation involves estimation of both regression and covariance parameters.

Gaussian and some non Gaussian Random fields can be analyzed using the `Geomodels` package. Among them gamma, Weibull, log-Gaussian, binomial, negative binomial, skewGaussian, StudenT and circular random fields can be analyzed.


# cover: assets/images/radhakrishna.jpg
# logo: assets/images/logo.png
# favicon: assets/images/favicon.png
baseurl: "/GeoModels/" # the subpath of your site, e.g. /blog/ or / for root url: "https://victormoralesonate.github.io" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

# Social
facebook: facebook
twitter: twitter
github:  github

#Additional Pages
resources: resources
install: install
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
parse_block_html: true

plugins:
- jekyll-paginate


# Settings for rake task
safe: False
lsi: False
username: VictorMoralesOnate #github username
repo: GeoModels #github repository
branch: master #branch
relative_source: ../GeoModels/ #source directory
destination: ../VictorMoralesOnate/GeoModels/ #destination directory
production_url:  https://victormoralesonate.github.io
source_url:  https://github.com/VictorMoralesOnate #source repository url

exclude:
- README.md
- Rakefile
- Gemfile
- Gemfile.lock
- changelog.md
- "*.Rmd"
- vendor
- .travis.yml
